# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

jobs: 
- job:
  pool:
    vmImage: ubuntu-latest
  displayName: "build"
  timeoutInMinutes: 360
  steps:
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true
      architecture: 'x64'
  - task: Bash@3
    timeoutInMinutes: 360
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        make docker
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/RELEASE/stretch/arm64/'
      ArtifactName: 'dent'
      publishLocation: 'Container'
