
###############################################################################
#
# Inclusive Makefile for the arm64_marvell_ac5x_db module.
#
# Autogenerated 2022-02-03 14:26:10.485397
#
###############################################################################
arm64_marvell_ac5x_db_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(arm64_marvell_ac5x_db_BASEDIR)module/make.mk
include $(arm64_marvell_ac5x_db_BASEDIR)module/src/make.mk
include $(arm64_marvell_ac5x_db_BASEDIR)module/auto/make.mk

